name: Test Container Image

on:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build and push Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}
            GIT_REPOSITORY_URL=https://github.com/${{ github.repository }}
            VERSION=${{ github.ref_name }}
          push: false
